# Generated by Django 2.2.7 on 2019-11-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gu_title', models.CharField(max_length=10, verbose_name='구')),
                ('dong_title', models.CharField(max_length=10, verbose_name='동')),
                ('living_pop', models.IntegerField(null=True, verbose_name='인구')),
                ('area', models.IntegerField(null=True, verbose_name='km2')),
                ('density', models.IntegerField(null=True, verbose_name='인구밀도')),
            ],
        ),
    ]
