# Generated by Django 2.2.7 on 2019-11-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chu',
            name='area',
            field=models.FloatField(null=True, verbose_name='m2'),
        ),
    ]
