# Generated by Django 2.2.7 on 2019-11-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chu', '0002_auto_20191116_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chu',
            name='area',
            field=models.FloatField(null=True, verbose_name='km2'),
        ),
    ]
