# Generated by Django 2.2.7 on 2019-11-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chu', '0003_auto_20191116_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='chu',
            name='high',
            field=models.CharField(blank=True, max_length=10, verbose_name='정도'),
        ),
    ]
