# Generated by Django 2.2.3 on 2019-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maechul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu_title', models.CharField(max_length=10, verbose_name='구')),
                ('dong_title', models.CharField(max_length=10, verbose_name='동')),
                ('classification', models.CharField(max_length=10, verbose_name='업종')),
                ('prev_year', models.IntegerField(null=True, verbose_name='작년')),
                ('cur_year', models.IntegerField(null=True, verbose_name='올해')),
            ],
        ),
    ]
