# Generated by Django 2.2.3 on 2019-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucheon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30, verbose_name='소재지')),
                ('code', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seoul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30, verbose_name='소재지')),
                ('code', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
