# Generated by Django 2.2.3 on 2019-10-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='상가명')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='소재지')),
                ('area', models.CharField(blank=True, max_length=8, null=True, verbose_name='면적')),
                ('Sector', models.CharField(blank=True, max_length=8, null=True, verbose_name='현 업종')),
                ('option', models.TextField(blank=True, null=True, verbose_name='옵션')),
                ('date', models.CharField(blank=True, max_length=8, null=True, verbose_name='입주 가능일')),
                ('floor', models.CharField(blank=True, max_length=5, null=True, verbose_name='해당층')),
                ('desc', models.TextField(verbose_name='매물 특징')),
                ('price', models.CharField(max_length=20, verbose_name='가격')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
