# Generated by Django 2.2.3 on 2019-10-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forSale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='area',
            field=models.CharField(max_length=8, verbose_name='면적'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=30, verbose_name='소재지'),
        ),
    ]
