# Generated by Django 2.2.3 on 2019-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forSale', '0003_auto_20191011_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.AddField(
            model_name='item',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='부동산 전화번호'),
        ),
    ]
