# Generated by Django 2.2.3 on 2019-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forSale', '0004_auto_20191011_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lat',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lng',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
