# Generated by Django 2.2.3 on 2019-11-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forSale', '0006_auto_20191113_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
    ]
