# Generated by Django 2.2.3 on 2019-10-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_juicy_tomntoms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Franchise',
        ),
    ]
