# Generated by Django 2.2.3 on 2019-10-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_auto_20191002_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juicy',
            options={'verbose_name': '쥬씨'},
        ),
        migrations.AlterModelOptions(
            name='tomntoms',
            options={'verbose_name': '탐앤탐스'},
        ),
    ]
