# Generated by Django 2.2.3 on 2019-10-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0005_auto_20191002_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juicy',
            options={'verbose_name_plural': 'JUICY'},
        ),
        migrations.AlterModelOptions(
            name='tomntoms',
            options={'verbose_name_plural': 'TOMNTOMS'},
        ),
    ]
