# Generated by Django 2.2.3 on 2019-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0007_momstouch_starbucks_subway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ediya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'EDIYA',
            },
        ),
        migrations.CreateModel(
            name='Gongcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'GONGCHA',
            },
        ),
        migrations.CreateModel(
            name='Mrsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MRSD',
            },
        ),
        migrations.CreateModel(
            name='Sinjeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'SINJEON',
            },
        ),
        migrations.RenameModel(
            old_name='TomNToms',
            new_name='Caffebene',
        ),
        migrations.AlterModelOptions(
            name='caffebene',
            options={'verbose_name_plural': 'CAFFEBENE'},
        ),
    ]
