# Generated by Django 2.1.5 on 2019-10-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post__id', '-id']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='post',
        ),
    ]
