# Generated by Django 2.1.5 on 2019-10-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20191013_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
