# Generated by Django 2.2.3 on 2019-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sang',
            name='gu_title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sang',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
