# Generated by Django 2.2.3 on 2019-11-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sang', '0002_auto_20191109_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sang',
            name='dong_title',
            field=models.CharField(max_length=10, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='sang',
            name='gu_title',
            field=models.CharField(max_length=10, verbose_name='구'),
        ),
    ]
