# Generated by Django 2.2.3 on 2019-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sang', '0005_auto_20191111_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='sang',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='sang',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True, verbose_name='경도'),
        ),
    ]
