# Generated by Django 2.2.3 on 2019-09-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20190922_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='board',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='likes',
        ),
    ]
